Dear <?php echo $this->fullname; ?>,<br /><br />

Your temporary password is: <strong><?php echo $this->password; ?></strong><br /><br />

<a href="<?php echo $this->link; ?>"><?php echo $this->link; ?></a><br /><br />

Please just to remind you change your password after successful authentication. <br /><br />

If you have problem with your temporary password please contact with the administrator.

Best Regards,<br />
Gruper.mk
