
<form action="" method="post">
    <dl>
        <?php echo $this->form->getElement('firstname'); ?>
        
        <?php echo $this->form->getElement('lastname'); ?>
        
        <?php echo $this->form->getElement('address'); ?>
                
        <?php echo $this->form->getElement('birthDate'); ?>
        
        <?php echo $this->form->getElement('title'); ?>
        
        <?php echo $this->form->getElement('gender'); ?>
        
        <?php echo $this->form->getElement('country_id'); ?>
        
        <?php echo $this->form->getElement('city_id'); ?>
        
        <?php echo $this->form->getElement('municipality_id'); ?>                        
        
        <?php echo $this->form->getElement('save'); ?>
    </dl>
</form>