<div id="forgotten-section">
    <header>
        <h2><?php echo $this->translate('FORGOTTEN PASSWORD'); ?></h2>
            
        <a href="#" id="forgotten-close">
            <img src="/images/close.png" alt="" /><?php echo $this->translate('затвори'); ?>
        </a>
    </header>    
    <div id="forgotten-container">
        <section class="forgotten-details">
            <p><?php echo $this->translate('You should receive confirmation email for final step of resetting password.'); ?></p>
            <p><?php echo $this->translate('Please click on the <strong>activation link</strong>  in the mail to verify your actions.'); ?></p>
        </section>
    </div>
</div>