<div id="forgotten-section">
    <?php if (count($this->form->getMessages()) > 0): ?>
        <div id="forgotten-section-errors">
            <img src="/images/error_x.png" alt="" />
            <?php echo $this->translate('Процесот на забравена парола не е комплетен. Ве молиме, обидете се повторно'); ?>
        </div>
    <?php endif; ?>    
    <header>
        <h2><?php echo $this->translate('FORGOTTEN PASSWORD'); ?></h2>
        
        <a href="#" id="forgotten-close">
            <img src="/images/close.png" alt="" /><?php echo $this->translate('затвори'); ?>
        </a>
    </header>
    
    <div id="forgotten-container">
        <section class="forgotten-details">
            
            <form action="<?php echo $this->url(array('module' => 'default', 
                'controller' => 'auth', 'action' => 'forgotten-password'), null, true); ?>" method="post" onsubmit="return doForgottenPassword(this);">
            <dl>
                <?php echo $this->form->getElement('email'); ?>

                <dt>&nbsp;</dt>
                <dd><?php echo $this->form->getElement('send'); ?></dd>
            </dl>
            </form>
            
        </section>    
    </div>
    
</div>