<div id="main-wrapper">
    <div class="social-reg-wrapper">
        <ul>
            <li><span><?php echo $this->translate('Create a BitLendingClub account:'); ?></span></li>
            <li>
                <a href="#" id="fblogin" class="fb-reg" title="<?php echo $this->translate('Login with Facebook'); ?>"><?php echo $this->translate('Facebook Login'); ?></a>

            </li>

            <li><a href="#" class="gplus-reg">&nbsp;</a></li>
        </ul>
    </div>
    <div class="reg-divider"><span><?php echo $this->translate("Don't have any of the above? Sing up with email."); ?></span></div>
    <?php if (count($this->form->getMessages()) > 0): ?>
    <div class="reg-divider"><span>
            <img src="/images/error_x.png" alt="" />
            <?php echo $this->translate('Registration is incomplete. Please, retry'); ?></span>
        </div>
    <?php endif; ?>
    <form class="reg-form" action="<?php echo $this->url(array('module' => 'default',
        'controller' => 'auth', 'action' => 'register'), null, true);
    ?>" method="post" onsubmit="return doRegister(this);">
        <?php echo $this->form->getElement('email'); ?>

        <?php echo $this->form->getElement('password'); ?>

        <?php echo $this->form->getElement('password_confirm'); ?>                

        <?php echo $this->form->getElement('firstname'); ?>

        <?php echo $this->form->getElement('lastname'); ?>

        <?php echo $this->form->getElement('username'); ?>

        <?php echo $this->form->getElement('address'); ?>
    
        <span><?php echo $this->translate('By signing up, I agree to BitLendingClub\'s <a href="#">Terms of Service.</a>');?></span>
        
        <?php echo $this->form->getElement('register'); ?>
    </form>
</div>
