<div id="register-section">
    <?php if (count($this->form->getMessages()) > 0): ?>
        <div id="register-section-errors">
            <img src="/images/error_x.png" alt="" />
            <?php echo $this->translate('Процесот на регистрација не е комплетен. Ве молиме, обидете се повторно'); ?>
        </div>
    <?php endif; ?>
    <header>
        <h2><?php echo $this->translate('РЕГИСТИРАЈ СЕ'); ?></h2>
        <?php echo $this->translate('Полињата означени со * се задолжителни '); ?>       
            
        <a href="#" id="register-close">
            <img src="/images/close.png" alt="" /><?php echo $this->translate('затвори'); ?>
        </a>
    </header>    
    <div id="register-container">
        <section class="register-details">

            <form action="<?php echo $this->url(array('module' => 'default', 
                'controller' => 'auth', 'action' => 'register'), null, true); ?>" method="post" onsubmit="return doRegister(this);">
            <dl>
                <?php echo $this->form->getElement('email'); ?>

                <?php echo $this->form->getElement('password'); ?>
                
                <?php echo $this->form->getElement('password_confirm'); ?>                
                
                <?php echo $this->form->getElement('firstname'); ?>
                
                <?php echo $this->form->getElement('lastname'); ?>
                
                <?php echo $this->form->getElement('captcha'); ?>

                <?php echo $this->form->getElement('remember_me'); ?>                        
            </dl>
            
            <p id="register-subscribe-section">
                <?php echo $this->form->getElement('subscription'); ?>    
            </p>
            
            <p>
                <?php $agreement = $this->form->getElement('is_agree_terms_conditions'); ?> 
                
                <?php echo $agreement; ?>
                
                <?php if (is_array($agreement->getMessages()) 
                        && count($agreement->getMessages()) > 0): ?>
                    <ul class="errors">
                        <?php foreach ($agreement->getMessages() as $message): ?>
                            <li><?php echo $message; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </p>
                
            <p id="register-button-section">
                <?php echo $this->form->getElement('register'); ?> 
                <?php echo $this->translate('или'); ?> 
                <a href="#" id="register-cancel"><?php echo $this->translate('откажи'); ?></a>
            </p>
            
            </form>
        </section> 
    </div>    
</div>