<div id="register-section">
    <header>
        <h2><?php echo $this->translate('THANK YOU FOR THE REGISTRATION'); ?></h2>
        <?php echo $this->translate('You can now browse latest deals and use available options on the site.'); ?>       
            
        <a href="#" id="register-close">
            <img src="/images/close.png" alt="" /><?php echo $this->translate('затвори'); ?>
        </a>
    </header>    
    <div id="register-container">
        <section class="register-details">
            <p><?php echo $this->translate('Check your email for processing final step of your registration.'); ?></p>
            <p><?php echo $this->translate('Please click on the <strong>activation link</strong> which you should recieve to your email address for account confirmation.'); ?></p>
        </section>
    </div>
</div>