<div id="register-section">
    <?php if (count($this->form->getMessages()) > 0): ?>
        <div id="register-section-errors">
            <img src="/images/error_x.png" alt="" />
            <?php echo $this->translate('Registration is incomplete. Please, retry'); ?>
        </div>
    <?php endif; ?>
    <header>
        <h2><?php echo $this->translate('Register'); ?></h2>
        <?php echo $this->translate('The fields marked with * are required'); ?>       
            
      
    </header>    
    <div id="register-container">
        <section class="register-details">

            <form action="<?php echo $this->url(array('module' => 'default', 
                'controller' => 'auth', 'action' => 'register'), null, true); ?>" method="post" onsubmit="return doRegister(this);">
            <dl>
                <?php echo $this->form->getElement('email'); ?>

                <?php echo $this->form->getElement('password'); ?>
                
                <?php echo $this->form->getElement('password_confirm'); ?>                
                
                <?php echo $this->form->getElement('firstname'); ?>
                
                <?php echo $this->form->getElement('lastname'); ?>
                
                <?php echo $this->form->getElement('username'); ?>
                
                <?php echo $this->form->getElement('address'); ?>
                
                <?php /* echo $this->form->getElement('captcha'); */?>

                <?php // echo $this->form->getElement('remember_me'); ?>                        
            </dl>
            
           
            
            <p id="register-button-section">
                <?php echo $this->form->getElement('register'); ?> 
                <?php echo $this->translate('or'); ?> 
                <a href="#" id="register-cancel"><?php echo $this->translate('cancel'); ?></a>
            </p>
            
            </form>
        </section> 
    </div>    
</div>