<?php
$this->headMeta()->appendName('keywords', $this->translate('Sitemap'));
$this->headMeta()->appendName('description', $this->translate('Sitemap'));
?>
<div id="page-wrapper" style="background: none;">    
    <div id="static-container">                
        <header id="page-header-static">
            <a href="<?php echo $this->url(array('controller' => "index", 'action' => 'index'), null, true); ?>" class="back-button"><?php echo $this->translate('Back'); ?></a>
            <h1><?php echo $this->translate('Sitemap'); ?></h1>
        </header>  

        <section id="page-container-static">
            <?php
                $this->navigation()->menu($this->navigation_front)->setPartial(array('sitemap/partials/sitemap.phtml', 'default'));
                echo $this->navigation()->menu($this->navigation_front)->render();
            ?>
        </section>        
    </div>    
</div>