<div id="main-wrapper">
    <div class="profile-content-wrapper profile-view-wrapper">
        <div class="ll-title">
            <h1 class="profile-icon"><?php echo $this->user->getFullname(); ?><span class="grey">'s profile</span></h1>
            <a href="#" class="grey-small-btn"><span>Back</span></a>
        </div>



        <div class="profile-content-right pcr-padding full-width-table mb-twenty">
            <div class="page-title">
                <h2 class="ll-second-title">Profile Summary</h2>
            </div>
            <div class="ls-row ls-row-bg first">
                <div class="ls-span ls-span6">
                    <span class="title">Active Loans</span>
                    <div class="description">฿ <?php echo $this->activeLoansBitcoins; ?> (<?php echo $this->activeLoansCount; ?>)</div>
                </div>
                <div class="ls-span ls-span6">
                    <span class="title">Repaid Loans</span>
                    <div class="description">฿<?php echo $this->repaidLoansBitcoins; ?> (<?php echo $this->repaidLoansCount; ?>)</div>
                </div>
                <div class="ls-span ls-span6">
                    <span class="title">Member Since</span>
                    <div class="description"><?php echo $this->user->getCreatedAt()->format('d M Y'); ?></div>
                </div>
                <div class="ls-span ls-span6">
                    <span class="title">Credentials</span>
                    <div class="description"><span>eBay: <span>mikemarkov</span></span> <span>facebook: <span>247 firends</span></span></div>
                </div>
            </div>
            <div class="ls-row ls-row-bg">
                <div class="ls-span ls-span6">
                    <span class="title">Payments Made</span>
                    <div class="description">฿<?php echo $this->paymentsBitcoins ?> (<?php echo $this->paymentsCount ?>)</div>
                </div>
                <div class="ls-span ls-span6">
                    <span class="title">Overdue Payments</span>
                    <div class="description">฿<?php echo $this->overduePaymentsBitcoins ?>   (<?php echo $this->overduePaymentsCount; ?>)</div>
                </div>
                <div class="ls-span ls-span6">
                    <span class="title">Reputation</span>
                    <div class="description"><?php echo $this->user->getRatingPercentage() ?>%</div>
                </div>
                <div class="ls-span ls-span6">
                    <span class="title">Account Ages</span>
                    <div class="description"><span>eBay: <span>6 years</span></span> <span>paypal: <span>2 years</span></span></div>
                </div>
            </div>
        </div>





        <div class="row">
            <div class="box box2 first">
                <div class="title">Credit Rating <span class="red"><?php echo $this->user->getCreditRating(); ?></span><span class="divider">/</span><span class="green">10</span></div>
                <div class="contnet">
                    <ol>
                        <?php foreach ($this->user->getDocuments() as $document) : ?>
                            <li>
                                <?php echo $document->getDocumentType()->getDescription(); ?>:  <?php if ($document->getIsReviewed() !== null) : ?><span class="green">Yes</span> <?php else : ?><span class="red">No</span><?php endif; ?>
                            </li>
                        <?php endforeach; ?>
<!--						<li>Phone veriﬁed: <span class="red">No</span></li>-->
<!--                        <li>Address veriﬁed: <span class="red">No</span></li>-->
<!--						<li>Credit score veriﬁed: <span class="red">No</span></li>-->
                        <li>Facebook: <?php if ($this->user->getFbUserId() == null || $this->user->getFbUserId() == 0) : ?><span class="red">No</span> <?php else : ?> <span class="green">Yes</span> <?php endif; ?></li>
                        <li>Google +: <span class="red">No</span></li>
                    </ol>
                </div>
            </div>
            <div class="box box1">
                <div class="title">Reputation <span class="red"><?php echo $this->user->getRatingPercentage() ?> %</span></div>
                <div class="contnet">
                    <ul>
                        <li>Positive: <span class="green"><?php echo $this->user->getPositiveRating() ?></span></li>
                        <li>Negative: <span class="red"><?php echo $this->user->getNegativeRating() ?></span></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row">
            <!--			<div class="box box1 first">
                            <div class="title">Verified Assets</div>
                            <div class="contnet">
                                <ul>
                                    <li>Exchange: <span>- - -</span></li>
                                    <li>Total sell value: <span>0.0</span></li>
                                    <li>Total buy value: <span>0.0</span></li>
                                    <li>Last update: <span>- - -</span></li>
                                </ul>
                            </div>
                        </div>-->
            <div class="box box1">
                <div class="title">Credentials</div>
                <div class="contnet">
                    <ul>
<!--						<li>PayPal: <span>almost 12 years</span></li>-->
                        <li>eBay: <span>about 14 years</span></li>
                        <li>Facebook: <span>244 friends</span></li>
<!--						<li>Linkedin: <span>78 connections</span></li>-->
                    </ul>
                </div>
            </div>
            <div class="box box1">
                <div class="title">eBay Feedback</div>
                <div class="contnet">
                    <ul>
                        <li>eBay profile: <span>mikemarkov (64)</span></li>
                    </ul>
                </div>
            </div>
        </div>




        <div class="profile-content-right pcr-padding full-width-table mb-twenty profile-view-table">
            <div class="page-title">
                <h2 class="ll-second-title">Aleksander Karaivanov's Loans and Listings</h2>
                <div class="table-toolbar">
                    <!--                    <div class="toolbar-sorter">
                                            <span>Show</span>
                                            <select>
                                                <option>10</option>
                                                <option>25</option>
                                                <option>50</option>
                                                <option>100</option>
                                            </select>
                                            <span>results.</span>
                                        </div>
                                        <div class="toolbar-search">
                                            <input type="text" />
                                            <a href="#"></a>
                                        </div>-->
                </div>
            </div>
            <table cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th>Listing title</th>
                        <th>Amount</th>
                        <th>% Funded</th>
                        <th>Term</th>
                        <th>Investors</th>

                        <th>Loan status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->user->getLoans() as $loan) : ?>
                        <tr>
                            <td><a href="#"><?php echo $loan->getTitle(); ?></a></td>
                            <td><?php echo $loan->getAmount(); ?></td>
                            <td><strong>72%</strong> funded<div class="funding-bg"><span style="width:72px;"></span></div></td>
                            <td><?php echo $loan->getTerm(); ?></td>
                            <td>
                                <?php if (count($loan->getInvestments()) != 0) : ?>
                                    <?php foreach ($loan->getInvestments() as $investment) : ?> 
                                        <a href="#"><?php echo $investment->getInvestor()->getUsername() ?></a><br />
                                    <?php endforeach; ?>
                                <? else : ?>
                                    <?php echo $this->translate('No Investments'); ?>
                                <? endif; ?>
                            </td>

                            <td><?php echo $loan->getStatus()->getName(); ?></td>
                        </tr>
                    <?php endforeach; ?>

                </tbody>
                <tfoot>
<!--                    <tr>
                        <td colspan="6" class="paging">
                            <div class="listing-infotext">Showing <strong>1</strong> to <strong>10</strong> of  <span>44 entries</span></div>
                            <ul>
                                 pagination next/previous classes ( .prev, .no-prev, .next, .no-next ) 
                                <li><a href="#" class="arr no-prev"></a></li>
                                <li class="current">1</li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#" class="arr next"></a></li>
                            </ul>
                        </td>
                    </tr>-->
                </tfoot>
            </table>
        </div>



        <div class="profile-content-right pcr-padding full-width-table mb-twenty profile-view-table">
            <div class="page-title">
                <h2 class="ll-second-title">Aleksander Karaivanov's Ratings</h2>
                <!--                <div class="table-toolbar">
                                    <div class="toolbar-sorter">
                                        <span>Show</span>
                                        <select>
                                            <option>10</option>
                                            <option>25</option>
                                            <option>50</option>
                                            <option>100</option>
                                        </select>
                                        <span>results.</span>
                                    </div>
                                    <div class="toolbar-search">
                                        <input type="text" />
                                        <a href="#"></a>
                                    </div>
                                </div>-->
            </div>
            <table cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th>From</th>
                        <th>To</th>
                        <th>Last update</th>
                        <th>Rating</th>
                        <th>Comment</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->ratings as $rating) : ?>
                        <tr>
                            <td><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index', 'id' => $rating->getCommenter()->getId())); ?>"><?php echo $rating->getCommenter()->getFullname(); ?></a></td>
                            <td><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index', 'id' => $rating->getUser()->getId())); ?>"><?php echo $rating->getUser()->getFullname(); ?></a></td>
                            <td>2013-02-03 11:27:55 UTC</td>
                            <td><?php echo $rating->getRating(); ?></td>
                            <td><?php echo $rating->getComment(); ?></td>
                        </tr>
                    <?php endforeach; ?>

                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6" class="paging">

                            <?php
                            echo $this->paginationControl(
                                    $this->ratings, 'Sliding', 'partials/paginator.phtml');
                            ?>
                            <!--                            <ul>
                                                             pagination next/previous classes ( .prev, .no-prev, .next, .no-next ) 
                                                            <li><a href="#" class="arr no-prev"></a></li>
                                                            <li class="current">1</li>
                                                            <li><a href="#">2</a></li>
                                                            <li><a href="#">3</a></li>
                                                            <li><a href="#">4</a></li>
                                                            <li><a href="#" class="arr next"></a></li>
                                                        </ul>-->
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div class="profile-content-right pcr-padding full-width-table">
            <div class="button-row">
                <span>Would you like to rate this user.</span>
                <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'rate', 'id' => $this->user->getId())); ?>" class="green-btn"><span>Rate user</span></a>
            </div>
        </div>



    </div>	
</div>