<div id="main-wrapper">
	<div class="profile-content-wrapper profile-view-wrapper">
		<div class="ll-title">
            <h1 class="profile-icon"><?php echo $this->user->getFullname(); ?><span class="grey">'s profile</span></h1>
			<a href="#" class="grey-small-btn"><span>Back</span></a>
		</div>



		<div class="profile-content-right pcr-padding full-width-table mb-twenty">
			<div class="page-title">
				<h2 class="ll-second-title">Profile Summary</h2>
			</div>
			<div class="ls-row ls-row-bg first">
				<div class="ls-span ls-span6">
					<span class="title">Active Loans</span>
					<div class="description">฿0.00 (0)</div>
				</div>
				<div class="ls-span ls-span6">
					<span class="title">Repaid Loans</span>
					<div class="description">฿0.00 (0)</div>
				</div>
				<div class="ls-span ls-span6">
					<span class="title">Member Since</span>
                    <div class="description"><?php echo $this->user->getCreatedAt()->format('d M Y'); ?></div>
				</div>
				<div class="ls-span ls-span6">
					<span class="title">Credentials</span>
					<div class="description"><span>eBay: <span>mikemarkov</span></span> <span>facebook: <span>247 firends</span></span></div>
				</div>
			</div>
			<div class="ls-row ls-row-bg">
				<div class="ls-span ls-span6">
					<span class="title">Payments Made</span>
					<div class="description">฿0.00 (0)</div>
				</div>
				<div class="ls-span ls-span6">
					<span class="title">Overdue Payments</span>
					<div class="description">฿0.00 (0)</div>
				</div>
				<div class="ls-span ls-span6">
					<span class="title">Reputation</span>
					<div class="description">100%</div>
				</div>
				<div class="ls-span ls-span6">
					<span class="title">Account Ages</span>
					<div class="description"><span>eBay: <span>6 years</span></span> <span>paypal: <span>2 years</span></span></div>
				</div>
			</div>
		</div>





		<div class="row">
			<div class="box box2 first">
				<div class="title">Credit Rating <span class="red">2</span><span class="divider">/</span><span class="green">10</span></div>
				<div class="contnet">
					<ol>
						<li>Identity veriﬁed: <span class="green">Yes</span></li>
<!--						<li>Phone veriﬁed: <span class="red">No</span></li>-->
						<li>Address veriﬁed: <span class="red">No</span></li>
<!--						<li>Credit score veriﬁed: <span class="red">No</span></li>-->
						<li>Facebook: <span class="red">No</span></li>
<!--						<li>LinkedIn: <span class="red">No</span></li>-->
					</ol>
				</div>
			</div>
			<div class="box box1">
				<div class="title">Reputation <span class="red">-35%</span></div>
				<div class="contnet">
					<ul>
						<li>Positive: <span class="green">12</span></li>
						<li>Negative: <span class="red">27</span></li>
					</ul>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="box box1 first">
				<div class="title">Verified Assets</div>
				<div class="contnet">
					<ul>
						<li>Exchange: <span>- - -</span></li>
						<li>Total sell value: <span>0.0</span></li>
						<li>Total buy value: <span>0.0</span></li>
						<li>Last update: <span>- - -</span></li>
					</ul>
				</div>
			</div>
			<div class="box box1">
				<div class="title">Credentials</div>
				<div class="contnet">
					<ul>
<!--						<li>PayPal: <span>almost 12 years</span></li>-->
						<li>eBay: <span>about 14 years</span></li>
						<li>Facebook: <span>244 friends</span></li>
<!--						<li>Linkedin: <span>78 connections</span></li>-->
					</ul>
				</div>
			</div>
			<div class="box box1">
				<div class="title">eBay Feedback</div>
				<div class="contnet">
					<ul>
						<li>eBay profile: <span>mikemarkov (64)</span></li>
					</ul>
				</div>
			</div>
		</div>




		<div class="profile-content-right pcr-padding full-width-table mb-twenty profile-view-table">
			<div class="page-title">
				<h2 class="ll-second-title">Aleksander Karaivanov's Loans and Listings</h2>
				<div class="table-toolbar">
					<div class="toolbar-sorter">
						<span>Show</span>
						<select>
							<option>10</option>
							<option>25</option>
							<option>50</option>
							<option>100</option>
						</select>
						<span>results.</span>
					</div>
					<div class="toolbar-search">
						<input type="text" />
						<a href="#"></a>
					</div>
				</div>
			</div>
			<table cellspacing="0" cellpadding="0">
				<thead>
					<tr>
						<th>Listing title</th>
						<th>Amount</th>
						<th>Rate</th>
						<th>Term</th>
						<th>Investors</th>
						<th>Funded</th>
						<th>Loan status</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><a href="#">ZIGGAP - Fast Secure Exchanges and Conversion</a></td>
						<td>1820.0000</td>
						<td>7%</td>
						<td>- - -</td>
						<td><a href="#">Jimmy</a></td>
						<td><strong>72%</strong> funded<div class="funding-bg"><span style="width:72px;"></span></div></td>
						<td>- - -</td>
					</tr>
					<tr>
						<td><a href="#">ZIGGAP - Fast Secure Exchanges</a></td>
						<td>1820.0000</td>
						<td>7%</td>
						<td>- - -</td>
						<td><a href="#">Lion</a></td>
						<td><strong>22%</strong> funded<div class="funding-bg"><span style="width:22px;"></span></div></td>
						<td>- - -</td>
					</tr>
					<tr>
						<td><a href="#">ZIGGAP - Fast Secure Exchanges and Conversion</a></td>
						<td>1820.0000</td>
						<td>7%</td>
						<td>- - -</td>
						<td><a href="#">River</a>, <a href="#">Salomon Tester</a></td>
						<td><strong>37%</strong> funded<div class="funding-bg"><span style="width:37px;"></span></div></td>
						<td>- - -</td>
					</tr>
					<tr>
						<td><a href="#">ZIGGAP - Fast Secure</a></td>
						<td>1820.0000</td>
						<td>7%</td>
						<td>- - -</td>
						<td><a href="#">Stanson</a></td>
						<td><strong>100%</strong> funded<div class="funding-bg"><span style="width:100px;"></span></div></td>
						<td>- - -</td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<td colspan="6" class="paging">
							<div class="listing-infotext">Showing <strong>1</strong> to <strong>10</strong> of  <span>44 entries</span></div>
							<ul>
								<!-- pagination next/previous classes ( .prev, .no-prev, .next, .no-next ) -->
								<li><a href="#" class="arr no-prev"></a></li>
								<li class="current">1</li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">4</a></li>
								<li><a href="#" class="arr next"></a></li>
							</ul>
						</td>
					</tr>
				</tfoot>
			</table>
		</div>



		<div class="profile-content-right pcr-padding full-width-table mb-twenty profile-view-table">
			<div class="page-title">
				<h2 class="ll-second-title">Aleksander Karaivanov's Ratings</h2>
				<div class="table-toolbar">
					<div class="toolbar-sorter">
						<span>Show</span>
						<select>
							<option>10</option>
							<option>25</option>
							<option>50</option>
							<option>100</option>
						</select>
						<span>results.</span>
					</div>
					<div class="toolbar-search">
						<input type="text" />
						<a href="#"></a>
					</div>
				</div>
			</div>
			<table cellspacing="0" cellpadding="0">
				<thead>
					<tr>
						<th>From</th>
						<th>To</th>
						<th>Last update</th>
						<th>Rating</th>
						<th>Comment</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><a href="#">ZIGGAP</a></td>
						<td><a href="#">Aleksander</a></td>
						<td>2013-02-03 11:27:55 UTC</td>
						<td>10</td>
						<td>great lender/borrower</td>
						<td>- - -</td>
					</tr>
					<tr>
						<td><a href="#">Aleksander Karaivanov</a></td>
						<td><a href="#">Joel</a></td>
						<td>2013-01-21 12:22:09 UTC</td>
						<td>8</td>
						<td>Thank you</td>
						<td>- - -</td>
					</tr>
					<tr>
						<td><a href="#">ZIGGAP</a></td>
						<td><a href="#">Aleksander</a></td>
						<td>2013-02-03 11:27:55 UTC</td>
						<td>10</td>
						<td>great lender/borrower</td>
						<td>- - -</td>
					</tr>
					<tr>
						<td><a href="#">Aleksander Karaivanov</a></td>
						<td><a href="#">Joel</a></td>
						<td>2013-01-21 12:22:09 UTC</td>
						<td>8</td>
						<td>Thank you</td>
						<td>- - -</td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<td colspan="6" class="paging">
							<div class="listing-infotext">Showing <strong>1</strong> to <strong>10</strong> of  <span>44 entries</span></div>
							<ul>
								<!-- pagination next/previous classes ( .prev, .no-prev, .next, .no-next ) -->
								<li><a href="#" class="arr no-prev"></a></li>
								<li class="current">1</li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">4</a></li>
								<li><a href="#" class="arr next"></a></li>
							</ul>
						</td>
					</tr>
				</tfoot>
			</table>
		</div>

		<div class="profile-content-right pcr-padding full-width-table">
			<div class="button-row">
				<span>Would you like to rate this user.</span>
				<a href="#" class="green-btn"><span>Rate user</span></a>
			</div>
		</div>



	</div>	
</div>