<?php $rateForm = $this->form; ?>
<div id="main-wrapper">
<!--	<ul id="tabs-nav">
		<li><a href="#"><span class="dashboard-icon">Dashboard</span></a></li>
		<li><a href="#"><span class="crating-icon">Credit rating</span></a></li>
		<li class="selected"><a href="#"><span class="rep-icon">Reputation</span></a></li>
		<li><a href="#"><span class="overview-icon">Investments</span></a></li>
		<li><a href="#"><span class="loan-icon">Loans</span></a></li>
		<li><a href="#"><span class="automated-plan-icon">Settings</span></a></li>
	</ul>-->
	<div class="profile-content-wrapper">
		<div class="sidebar-left profile-sidebar">
			<!--div class="sidebar-infoboard mb-twenty">
				<div class="sidebar-msg">
					<span>Import your Bitcoin OTC Reputation</span>
					<a href="#" class="green-btn"><span>Import</span></a>
				</div>
			</div-->
			<div class="sidebar-infoboard">
				<div class="title">Reputation <span class="red"><?php echo $this->user->getRatingPercentage();?> %</span></div>
				<ul>
					<li>Positive: <span class="green"><?php echo $this->user->getPositiveRating(); ?></span></li>
					<li>Negative: <span class="red"><?php echo $this->user->getNegativeRating(); ?></span></li>
				</ul>
			</div>
		</div>
		<div class="profile-content-right">
			<h1>Rate user</h1>
			<p>Only users with a <strong>rating greater than 3</strong> can rate others.</p>
			<p>You can only rate a user <strong>you had some interaction with</strong> (invested or borrowed from him).</p>
			<form action="<?php
            echo $this->url(array('module' => 'default',
                'controller' => 'user', 'action' => 'rate'), null, true);
            ?>" method="post">
				<div class="field-box">
					<label><span class="red">*</span> User Alias:</label>
					<?php echo $rateForm->getElement('user_id'); ?>
				</div>
				<div class="field-box">
					<label><span class="red">*</span> Rating:</label>
					<input name="rating" id="rating" type="number" min="-10" max="10" class="input-short" />
					<span class="info c-both mt-five">Value between -10 and 10.</span>
				</div>
				<div class="field-box">
					<label><span class="red">*</span> Comment:</label>
					<?php echo $rateForm->getElement('comment');?>
				</div>
				<div class="buttons-set">
					<a href="#" onclick="$(this).parents('form').submit();" class="green-btn"><span>Rate user</span></a>
					<span class="required"><span class="red">*</span> Required fields</span>
					<a href="javascript:history.go(-1)" class="back-link">Back</a>
				</div>
			</form>
		</div>
	</div>
</div>