<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />        
        <?php
        echo $this->headScript()
                ->prependFile('/js/jquery-1.7.1.min.js')
                ->appendFile('/js/jquery-ui-1.8.18.custom.min.js')
                ->appendFile('/js/jquery.filedrop.js')
                ->appendFile('/js/jqModal.js')
                ->appendFile('/js/jquery-ui-timepicker-addon.js')
                ->appendFile('/js/jquery.slug.js')
                ->appendFile('/js/admin.js')
                ->appendFile('/js/gp.search.js');
        ?>
        <?php
        echo $this->headLink()
                ->prependStylesheet('/styles/reset.css')
                ->appendStylesheet('/styles/admin.css')
                ->appendStylesheet('/styles/all.css')
                ->appendStylesheet('/styles/jqModal.css')
                ->appendStylesheet('/styles/smoothness/jquery-ui-1.8.18.custom.css');
        ?>
        <script src="http://cdn.pubnub.com/pubnub-3.1.min.js"></script>
        <title><?php echo $this->translate('It-instructor Administration Panel'); ?></title>
        <base href="<?php echo $this->url(array('module' => 'admin'), null, true); ?>/" />
    </head>
    <body>        
         
        
<section style="margin-top:400px;margin-left:700px;">
    <header><h2>IT-Instructor Admin</h2></header>
    <form action="" method="post">
        <?php echo $this->form->getElement('email'); ?>
        <?php echo $this->form->getElement('password'); ?>
        <?php echo $this->form->getElement('login'); ?>
    </form>
</section>
        
            </body>
</html>