<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />        
        <?php
        echo $this->headScript()
                ->prependFile('/js/jquery-1.7.1.min.js')
                ->appendFile('/js/jquery-ui-1.8.18.custom.min.js')
                ->appendFile('/js/jquery.filedrop.js')
                ->appendFile('/js/jqModal.js')
                ->appendFile('/js/jquery-ui-timepicker-addon.js')
                ->appendFile('/js/jquery.slug.js')
                ->appendFile('/js/admin.js')
                ->appendFile('/js/gp.search.js');
        ?>
        <?php
        echo $this->headLink()
                ->prependStylesheet('/styles/reset.css')
                ->appendStylesheet('/styles/admin.css')
                ->appendStylesheet('/styles/all.css')
                ->appendStylesheet('/styles/jqModal.css')
                ->appendStylesheet('/styles/bootstrap.min.css')
                ->appendStylesheet('/styles/bootstrap-responsive.css')
                 ->appendStylesheet('/styles/main.css')
                ->appendStylesheet('/styles/smoothness/jquery-ui-1.8.18.custom.css');
        ?>
        <script src="http://cdn.pubnub.com/pubnub-3.1.min.js"></script>
        <title><?php echo $this->translate('BLC Admin Panel'); ?></title>
        <base href="<?php echo $this->url(array('module' => 'admin'), null, true); ?>/" />
    </head>
    <body id="login">        
         
        
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span4">&nbsp;</div>
        <div class="span4">
            <div class="page-header">
                <h3>BLC Admin Panel</h3>
            </div>
            <div class="box" style="margin-bottom:500px;">
                <h4 class="box-header round-top">Login</h4>
                <div class="box-container-toggle">
                    <div class="box-content">
    <form class="well form-search" action="" method="post">
        <?php echo $this->form->getElement('email'); ?>
        <?php echo $this->form->getElement('password'); ?>
        <?php echo $this->form->getElement('login'); ?>
    </form>
</div>
                </div>
            </div>
            <!--/span-->
            <div class="span4">&nbsp;</div>
        </div>
        <!--/span-->
    </div>
<footer>
</footer>
</div>
            </body>
</html>