    <!--==============================slider================================-->
    <div id="main-page-slider">
    	<div class="slider-holder">
        	<div id="slider-container">
                <div id="coin-slider">
                    <img src="/images/slide-1.jpg" alt="">
                    <img src="/images/slide-2.jpg" alt="">
                    <img src="images/slide-3.jpg" alt="">
                    <img src="images/slide-4.jpg" alt="">
                    <img src="images/slide-5.jpg" alt="">
                </div>
            </div>
        </div>
        <div class="right-col">
            <div class="box-1">
                <h3 class="head-1"><?php echo $this->translate('Welcome'); ?></h3>
                <p class="text-1">
                    <?php echo $this->translate('We provide our clients with IT Instructors in order to deliver Cisco, IronPort, Checkpoint, HP, NetApp, ITIL, Microsoft,VMWare, Citrix, SAP, Oracle, CompTIA, CEH and CISSP Training Courses. <br /><br /> We provide IT Instructors in all technology areas, all our Instructors have many years of teaching experience in their technology fields and are certified to all vendor certification levels.'); ?> 
                </p>
<!--                <ul class="box-1-list">
                    <li><a href="#">Starting up</a></li>
                    <li><a href="#">Finance and grants</a></li>
                    <li><a href="#">Taxes, returns &amp; payroll</a></li>
                    <li><a href="#">Employment &amp; skills</a></li>
                    <li><a href="#">Health, safety, premises</a></li>
                    <li><a href="#">Environment &amp; efficiency</a></li>
                </ul>-->
            </div>
        </div>
    </div>
    <!--==============================content================================-->
    <section id="content">
        <div class="container_12">
            <h3 class="hp-1">Choose your certified IT trainer by geolocation.</h3>
            <article class="a1" id="homeMap" style="overflow: hidden;">
                <h4 style="width: 861px; text-align: center; margin: 133px 0 0 20px; padding: 20px;  background: rgb(255, 255, 255); background: rgba(255, 255, 255, 0.9); font-size: 40px;">Comming soon ...</h4>

<!--                
                <div>
                	<div class="grid_3 alpha">
                    	<h6 class="p0">Global solutions</h6>
                        <strong class="str1">
                        	Let us cooperate!
                        </strong>
                        <ul class="list-1">
                        	<li><a href="#">Management Consulting</a></li>
                            <li><a href="#">Policy and Regulatory Analysis</a></li>
                            <li><a href="#">Market Assessment</a></li>
                            <li><a href="#">Program Management</a></li>
                            <li><a href="#">Regulatory Support</a></li>
                        </ul>
                        <a href="more.html" class="button">Learn more</a>
                    </div>
                    <div class="grid_3">
                    	<h6 class="p0">Premium services</h6>
                        <strong class="str1">
                        	We work for your profit!
                        </strong>
                        <ul class="list-1">
                        	<li><a href="#">Scientific and Risk Assessment</a></li>
                            <li><a href="#">Change Management</a></li>
                            <li><a href="#">Information Technology</a></li> 
                            <li><a href="#">Strategic Communications</a></li>
                            <li><a href="#">Training and Education</a></li>
                        </ul>
                        <a href="more.html" class="button">Learn more</a>
                    </div>
                    <div class="grid_3">
                    	<h6 class="p0">Perfect opportunities</h6>
                        <strong class="str1">
                        	Advance your business!
                        </strong>
                        <ul class="list-1">
                        	<li><a href="#">Exploit your ideas</a></li>
                            <li><a href="#">IT &amp; e-commerce</a></li>
                            <li><a href="#">Sales and marketing</a></li>
                            <li><a href="#">International trade</a></li>
                            <li><a href="#">Grow your business</a></li>
                        </ul>
                        <a href="more.html" class="button">Learn more</a>
                    </div>
                    <div class="grid_3 omega">
                    	<h6 class="p0">News headlines</h6>
                        <strong class="str1">
                        	What’s new?
                        </strong>
                        <ul class="list-1 extra">
                        	<li><a href="more.html">Second Quarter 2011 Fixed Income Investor Review</a></li>
                            <li><a href="more.html">Globobiz Citi Upbeat on Economy Prospects for China</a></li>
                            <li><a href="more.html">Globobiz Ventures Makes Strategic Investment</a></li>
                        </ul>
                        <a href="more.html" class="button">More news</a>
                    </div>
                    <div class="clear"></div>
                </div>
-->

            </article>
        </div>
    </section>