<?php $page = $this->currentPage; ?>

<?php 
$this->headMeta()->appendName('keywords', $page->getMetaKeywords());
$this->headMeta()->appendName('description', $page->getMetaDescription());
?>

    <h2></h2>
    
<div id="main-wrapper">
	<!--div class="sidebar-left">
		<span class="sidebar-nav-title">About us</span>
		<ul id="sidebar-nav">
			<li>
				<a href="#">Our Company</a>
			</li>
			<li class="selected">
				<a href="#">History</a>
			</li>
			<li>
				<a href="#">Press</a>
			</li>
			<li>
				<a href="#">Blog</a>
			</li>
		</ul>
		<div class="sidebar-banner-wrapper">
			<a href="#"><img src="images/sample-images/sidebar-banner.png" /></a>
		</div>
	</div-->
	<div class="content-right">
		<h1><?php echo $page->getTitle();?></h1>
		<?php echo $page->getContent();?>
	</div>
</div>