
<?php $view = Zend_Layout::getMvcInstance()->getView(); ?>
<?php $selPage = Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); 
?>
<li class="<?php echo ($selPage == "index" ? "active main-nav-arrow" : ""); ?>">
    <a class="main-menu-link" href="<?= $view->url(array('module' => 'admin'), null, true) ?>">
        <div class="main-nav-icon-big"><img  src="/images/glyphicons/glyphicons_138_computer_proces.png"></div>
        Home
    </a>
</li>  
<li  class="<?php echo ($selPage == "users" ? "active main-nav-arrow" : ""); ?>">
    <a class="main-menu-link" href="<?php echo $view->url(array('controller' => 'users', 'action' => 'index', 'module' => 'admin'), null, true);?>">
        <div class="main-nav-icon-big"><img src="/images/glyphicons/glyphicons_003_user.png"></div>
        Users
    </a>
</li>
<li  class="<?php echo ($selPage == "documents" ? "active main-nav-arrow" : ""); ?>">
    <a class="main-menu-link" href="<?php echo $view->url(array('controller' => 'documents', 'action' => 'index', 'module' => 'admin'), null, true);?>">
        <div class="main-nav-icon-big"><img src="/images/glyphicons/glyphicons_039_notes.png"></div>
        Documents
    </a>
</li>
<li class="<?php echo ($selPage == "pages" ? "active main-nav-arrow" : ""); ?>">
    <a class="main-menu-link" href="<?php echo $view->url(array('controller' => 'pages', 'action' => 'index', 'module' => 'admin'), null, true);?>">
        <div class="main-nav-icon-big"><img src="/images/glyphicons/glyphicons_036_file.png"></div>
        Pages
    </a>
</li>