<?php $loan = $this->loan;?>
<div id="main-wrapper">
    <ul id="tabs-nav">
        <li><a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'overview'), null, true); ?>"><span class="overview-icon">Overview</span></a></li>
        <li class="selected"><a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'index'), null, true); ?>"><span class="browse-listings-icon">Browse Loan Listings</span></a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'create'), null, true); ?>"><span class="automated-plan-icon">Borrow</span></a></li>
    </ul>
    <div class="profile-content-wrapper">
        <div class="ll-title">
            <h1><?php echo $loan->getTitle();?></h1>
            <a href="javascript:history.go(-1)" class="grey-small-btn"><span>Back</span></a>
        </div>



        <div class="profile-content-right pcr-padding full-width-table mb-twenty">
            <div class="page-title">
                <h2 class="ll-second-title">Loan Summary</h2>
            </div>
            <div class="ls-row first">
                <div class="ls-span ls-span1">
                    <span class="title">Expires</span>
                    
                    <div class="description"><?php echo $loan->getExpirationDate()->format('Y-m-d');?><span class="grey2">/</span><?php echo $loan->getExpirationDate()->format('H:i');?><span class="grey">(in 3 days)</span></div>
                </div>
                <div class="ls-span ls-span2">
                    <span class="title">Status</span>
                    <div class="description">Listing <span class="green">Open</span></div>
                </div>
                <div class="ls-span ls-span3">
                    <span class="title">Term</span>
                    <div class="description">90 days</div>
                </div>
            </div>
            <div class="ls-row">
                <div class="ls-span ls-span1">
                    <span class="title">Payment</span>
                    <div class="description">BTC 4.77853<span class="grey2">/</span>every 7 days</div>
                </div>
                <div class="ls-span ls-span2">
                    <span class="title">Amount @ Rate</span>
                    <div class="description">1820.0000 @ 7.0%</div>
                </div>
                <div class="ls-span ls-span3">
                    <span class="title">% Funded</span>
                    <div class="description"><span class="f-left">35% funded</span><div class="funding-bg f-left"><span style="width:35px;"></span></div><span class="f-left grey">BTC 0.00000 left</span></div>
                </div>
            </div>
            <div class="ls-row">
                <div class="ls-span ls-span1">
                    <span class="title">User Loan Activity</span>
                    <div class="description"><a href="#">2 Active</a>, <a href="#">5 Repaid</a></div>
                </div>
                <div class="ls-span ls-span2">
                    <span class="title">User</span>
                    <div class="description"><a href="#">Profile</a></div>
                </div>
                <div class="ls-span ls-span4">
                    <span class="title">User Reputation</span>
                    <div class="description"><strong class="green">80%</strong> positive <span class="green">+10</span>, <span class="red">-2</span></div>
                </div>
                <div class="ls-span ls-span5">
                    <span class="title">BLC Rating</span>
                    <div class="description"><strong class="green">10</strong></div>
                </div>
            </div>
        </div>



        <div class="profile-content-right pcr-padding full-width-table mb-twenty">
            <div class="page-title">
                <h2 class="ll-second-title">Description</h2>
            </div>
            <div class="profile-content-wrapper">
                <p>Underestimated the amount I required for the inventory I wish to purchase so I am seeking an additional 60 BTC. You can see by my previous loans this was the case the last time I bought stock also and I had 2 or 3 loans running concurrently but all were paid back in advance with no issues.</p>
                <p>The total combined BTC of these two loans is alot less than I have had on loan also previously and I will continue to aggressively pre pay my debts, with this being no exception.</p>
                <p>This will most likely be repaid before the loan duration.</p>
            </div>
        </div>





        <div class="profile-content-right pcr-padding full-width-table mb-twenty">
            <div class="page-title">
                <h2 class="ll-second-title">Investments</h2>
                <div class="table-toolbar">
                    <div class="toolbar-sorter">
                        <span>Show</span>
                        <select>
                            <option>10</option>
                            <option>25</option>
                            <option>50</option>
                            <option>100</option>
                        </select>
                        <span>results.</span>
                    </div>
                    <div class="toolbar-search">
                        <input type="text" />
                        <a href="#"></a>
                    </div>
                </div>
            </div>
            <table cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th>To</th>
                        <th>Listing title</th>
                        <th>Amount</th>
                        <th>Rate</th>
                        <th>Term</th>
                        <th>Loan status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><a href="#">Jimmy</a></td>
                        <td><a href="#">ZIGGAP - Fast Secure Exchanges and Conversion</a></td>
                        <td>1820.0000</td>
                        <td>7%</td>
                        <td>- - -</td>
                        <td>- - -</td>
                    </tr>
                    <tr>
                        <td><a href="#">Lion</a></td>
                        <td><a href="#">ZIGGAP - Fast Secure Exchanges</a></td>
                        <td>1820.0000</td>
                        <td>7%</td>
                        <td>- - -</td>
                        <td>- - -</td>
                    </tr>
                    <tr>
                        <td><a href="#">River</a></td>
                        <td><a href="#">ZIGGAP - Fast Secure Exchanges and Conversion</a></td>
                        <td>1820.0000</td>
                        <td>7%</td>
                        <td>- - -</td>
                        <td>- - -</td>
                    </tr>
                    <tr>
                        <td><a href="#">Stanson</a></td>
                        <td><a href="#">ZIGGAP - Fast Secure</a></td>
                        <td>1820.0000</td>
                        <td>7%</td>
                        <td>- - -</td>
                        <td>- - -</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6" class="paging">
                            <div class="listing-infotext">Showing <strong>1</strong> to <strong>10</strong> of  <span>44 entries</span></div>
                            <ul>
                                <!-- pagination next/previous classes ( .prev, .no-prev, .next, .no-next ) -->
                                <li><a href="#" class="arr no-prev"></a></li>
                                <li class="current">1</li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#" class="arr next"></a></li>
                            </ul>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>


        <div class="profile-content-right pcr-padding full-width-table">
            <div class="page-title">
                <h2 class="ll-second-title">Comment</h2>
            </div>
            <div class="ls-row2">
                <textarea name="Comment" type="text" placeholder="Comment"></textarea>
                <div class="buttons-set">
                    <a href="#" class="green-btn"><span>Post comment</span></a>
                </div>
            </div>
            <div class="ls-row2">
                <span class="name-date"><a href="#">Jimmy</a><span class="grey2">/</span>21 January 2013</span>
                <span class="comment">Hi guys, I'm new here. Can anyone tell me exactly how interest is calculated? How often is it compounded?</span>
            </div>
            <div class="ls-row2">
                <span class="name-date"><a href="#">James Dean</a><span class="grey2">/</span>17 January 2013</span>
                <span class="comment">It is based the same as fixed rate mortgaging - read here http://en.wikipedia.org/wiki/Fixed-rate_mortgage#Pricing</span>
            </div>
            <div class="paging">
                <div class="listing-infotext">Showing <strong>1</strong> to <strong>10</strong> of  <span>44 entries</span></div>
                <ul>
                    <!-- pagination next/previous classes ( .prev, .no-prev, .next, .no-next ) -->
                    <li><a href="#" class="arr no-prev"></a></li>
                    <li class="current">1</li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#" class="arr next"></a></li>
                </ul>
            </div>
        </div>



    </div>







</div>