<?php $loan = $this->loan; ?>
<div id="main-wrapper">
    <ul id="tabs-nav">
        <li><a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'overview'), null, true); ?>"><span class="overview-icon">Overview</span></a></li>
        <li class="selected"><a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'index'), null, true); ?>"><span class="browse-listings-icon">Browse Loan Listings</span></a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'create'), null, true); ?>"><span class="automated-plan-icon">Borrow</span></a></li>
    </ul>
    <div class="profile-content-wrapper">
        <div class="ll-title">
            <h1><?php echo $loan->getTitle(); ?></h1>
            <a href="javascript:history.go(-1)" class="grey-small-btn"><span>Back</span></a>
            <a href="#" onclick="javascript:initInvestDialog(<?php echo $loan->getId();?>)" id="dash-invest" class="green-btn"><span>Invest</span></a>
        </div>



        <div class="profile-content-right pcr-padding full-width-table mb-twenty">
            <div class="page-title">
                <h2 class="ll-second-title">Loan Summary</h2>
            </div>
            <div class="ls-row first">
                <div class="ls-span ls-span1">
                    <span class="title">Expires</span>

                    <div class="description"><?php echo $loan->getExpirationDate()->format('Y-m-d'); ?><span class="grey2">/</span><?php echo $loan->getExpirationDate()->format('H:i'); ?><span class="grey">(in 3 days)</span></div>
                </div>
                <div class="ls-span ls-span2">
                    <span class="title">Status</span>
                    <div class="description">Listing <span class="green"><?php echo $loan->getStatus()->getName(); ?></span></div>
                </div>
                <div class="ls-span ls-span3">
                    <span class="title">Term</span>
                    <div class="description"><?php echo $loan->getTerm(); ?> days</div>
                </div>
            </div>
            <div class="ls-row">
                <div class="ls-span ls-span1">
                    <span class="title">Payment Frequency</span>
                    <div class="description">every <?php echo $loan->getFrequency(); ?> days</div>
                </div>
                <div class="ls-span ls-span2">
                    <!--span class="title">Amount @ Rate</span>
                    <div class="description">1820.0000 @ 7.0%</div-->
                </div>
                <div class="ls-span ls-span3">
                    <span class="title">% Funded</span>
                    <div class="description"><span class="f-left">35% funded</span><div class="funding-bg f-left"><span style="width:35px;"></span></div><span class="f-left grey">BTC 0.00000 left</span></div>
                </div>
            </div>
            <div class="ls-row">
                <div class="ls-span ls-span1">
                    <span class="title">User Loan Activity</span>
                    <div class="description"><a href="#">2 Active</a>, <a href="#">5 Repaid</a></div>
                </div>
                <div class="ls-span ls-span2">
                    <span class="title">User</span>
                    <div class="description"><a href="#"><?php echo $loan->getBorrower()->getFullname(); ?></a></div>
                </div>
                <div class="ls-span ls-span4">
                    <span class="title">User Reputation</span>
                    <div class="description"><strong class="green">80%</strong> positive <span class="green">+10</span>, <span class="red">-2</span></div>
                </div>
                <div class="ls-span ls-span5">
                    <span class="title">BLC Rating</span>
                    <div class="description"><strong class="green"><?php echo $loan->getBorrower()->getRating(); ?></strong></div>
                </div>
            </div>
        </div>



        <div class="profile-content-right pcr-padding full-width-table mb-twenty">
            <div class="page-title">
                <h2 class="ll-second-title">Description</h2>
            </div>
            <div class="profile-content-wrapper">
                <?php echo $loan->getDescription(); ?>
            </div>
        </div>




        <?php if (count($this->investments) > 0): ?>
            <div class="profile-content-right pcr-padding full-width-table mb-twenty">
                <div class="page-title">
                    <h2 class="ll-second-title">Investments</h2>
                    <div class="table-toolbar">
                        <!--div class="toolbar-sorter">
                            <span>Show</span>
                            <select>
                                <option>10</option>
                                <option>25</option>
                                <option>50</option>
                                <option>100</option>
                            </select>
                            <span>results.</span>
                        </div>
                        <div class="toolbar-search">
                            <input type="text" />
                            <a href="#"></a>
                        </div-->
                    </div>
                </div>

                <table cellspacing="0" cellpadding="0">
                    <thead>
                        <tr>
                            <th>To</th>
                            <th>Listing title</th>
                            <th>Amount</th>
                            <th>Rate</th>
                            <?php if($this->canEdit):?><th>Remove investment</th><?php endif;?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->investments as $investment): ?>
                            <tr>
                                <td><a href="#"><?php echo $investment->getInvestor()->getFullname(); ?></a></td>
                                <td><a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'browse', 'lid' => $loan->getId()), null, true); ?>"><?php echo $loan->getTitle(); ?></a></td>
                                <td><?php echo $investment->getAmount(); ?></td>
                                <td><?php echo $investment->getRate(); ?>%</td>
                                <?php if($this->canEdit):?><td><a href="#">Remove this investment</a></td><?php endif;?>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>

                </table>
            </div>

        <?php else: ?>
            <div class="profile-content-right pcr-padding full-width-table mb-twenty">
                <div class="page-title">
                    <h2 class="ll-second-title">Investments</h2>
                </div>
                <div class="profile-content-wrapper">
                    No investments yet.
                </div>
            </div>
        <?php endif; ?>

        <div class="profile-content-right pcr-padding full-width-table">
            <div class="page-title">
                <h2 class="ll-second-title">Comment</h2>
            </div>
            <div class="ls-row2">
                <form name="comment-form" action="<?php
        echo $this->url(array('module' => 'default',
            'controller' => 'loan', 'action' => 'comment'), null, true);
        ?>" method="post">
                          <?php echo $this->form->getElement('comment'); ?>
<?php echo $this->form->getElement('user_id'); ?>
                    <input type="hidden" name="loan_id" value="<?php echo $loan->getId(); ?>" id="loan_id"/>
                    <div class="buttons-set">
                        <a href="#" onclick="$(this).parents('form').submit();" class="green-btn"><span>Post comment</span></a>
                    </div>
            </div>
            <?php if (count($this->comments) > 0): ?>
    <?php foreach ($this->comments as $comment): ?>
                    <div class="ls-row2">
                        <span class="name-date"><a href="#"><?php echo $comment->getUser()->getFullname(); ?></a><span class="grey2">/</span><?php echo $comment->getPostedOn()->format('Y-m-d'); ?></span>
                        <span class="comment"><?php echo $comment->getComment(); ?></span>
                    </div>
    <?php endforeach; ?>
                <div class="paging">
                    <!--div class="listing-infotext">Showing <strong>1</strong> to <strong>10</strong> of  <span>44 entries</span></div-->

                    <?php
                    echo $this->paginationControl(
                            $this->comments, 'Sliding', 'partials/paginator.phtml');
                    ?>

                </div>

<?php else: ?>

                No comments added.

<?php endif; ?>
        </div>

    </div>







</div>