<div id="main-wrapper">
	
	<div class="profile-content-wrapper">
		<div class="full-width">
			<h1>Basic settings</h1>
			<form action="<?php echo $this->url(array('module' => 'default', 
                'controller' => 'loan', 'action' => 'create'), null, true); ?>" method="post">                
<div class="field-box">
                <?php echo $this->form->getElement('password'); ?>
                </div>
    <div class="field-box">
                <?php echo $this->form->getElement('password_confirm'); ?>                
                </div>
    <div class="field-box">
                <?php echo $this->form->getElement('firstname'); ?>
                </div>
    <div class="field-box">
                <?php echo $this->form->getElement('lastname'); ?>
                </div>
    <div class="field-box">
                <?php echo $this->form->getElement('username'); ?>
                </div>
    <div class="field-box">
                <?php echo $this->form->getElement('address'); ?>
                </div>
          <div class="buttons-set">     
           <?php echo $this->form->getElement('save'); ?>
		</div>		
					
				
			</form>
		</div>
	</div>
</div>

            
            
           
            
        