<?php $now = new DateTime(); ?>
<div id="main-wrapper">
    <ul id="tabs-nav">
        <li><a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'overview'), null, true); ?>"><span class="overview-icon">Overview</span></a></li>
        <li class="selected"><a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'index'), null, true); ?>"><span class="browse-listings-icon">Browse Loan Listings</span></a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'create'), null, true); ?>"><span class="automated-plan-icon">Borrow</span></a></li>
    </ul>
    <div class="page-title">
        <h1>Bitcoin Loan Listings</h1>
        <div class="table-toolbar">
            <!--div class="toolbar-sorter">
                <span>Show</span>
                <select>
                    <option>10</option>
                    <option>25</option>
                    <option>50</option>
                    <option>100</option>
                </select>
                <span>results.</span>
            </div>
            <div class="toolbar-search">
                <input type="text" />
                <a href="#"></a>
            </div-->
        </div>
    </div>
    <?php if (count($this->loans)): ?>


        <table id="listing-table" cellspacing="0" cellpadding="0">
            <thead>
                <tr>
                    <th>Title / Purpose, Term</th>
                    <th>Amount / Payment Type</th>
                    <th>% Funded</th>
                    <th>Time Left</th>
                    <th>Reputation</th>
                    <th>BLC Rating</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->loans as $loan):
                    $investPercent = Model_Loan::getInvestmentsAmount($loan->getInvestments(), true); ?>
                    <tr>
                        <td class="listing-title"><a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'browse', 'lid' => $loan->getId()), null, true); ?>"><?php echo $loan->getTitle(); ?></a><strong><?php echo $loan->getPurpose();?></strong>, <?php echo $loan->getTerm(); ?></td>
                        <td class="interest"><span><?php echo $loan->getAmount(); ?></span><?php echo $loan->getFrequency(); ?></td>
                        <!-- funding-bg / adding width to the span from 0 to 100 will fill the graphic  -->
                        <td><strong><?php echo $investPercent; ?>%</strong> funded<div class="funding-bg"><span style="width:<?php echo $investPercent; ?>px;"></span></div></td>
                        <td><strong><?php echo $now->diff($loan->getExpirationDate())->format('%R%d');?></strong> days</td>
                        <td><strong><?php echo $loan->getBorrower()->getRatingPercentage(); ?></strong> positive <div class="reputation-makrs"><span>+10</span>, <span>-2</span></div></td>
                        <td class="rating"><strong class="green-star">10</strong> <a href="#">Full<br/>rating</a></td>
                    </tr>
                <?php endforeach; ?>

            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6" class="paging">
                        <?php
                        echo $this->paginationControl(
                                $this->loans, 'Sliding', 'partials/paginator.phtml');
                        ?>
                        <!--div class="listing-infotext">Showing <strong>1</strong> to <strong>10</strong> of  <span>44 entries</span></div-->
                        
                    </td>
                </tr>
            </tfoot>
        </table>
    <?php else: ?>
        <div>No loans found.</div>
    <?php endif; ?>
</div>