<div id="overlay-block">
	<div class="login-wrapper">
		<div class="login-holder">
			<div id="show-login-holder">
				<div class="title">Invest</div>
				<form id="invest-form" action="<?php echo $this->url(array('module' => 'default', 
                'controller' => 'loan', 'action' => 'invest'), null, true); ?>" method="post" onsubmit="return doInvest(this);">
					<?php // echo $this->form->getElement('amount'); ?>
                    <input name="amount" type="number" min="0" max="" class="input-short" />
                <?php // echo $this->form->getElement('rate'); ?>
                    <input name="rate" type="number" min="0" class="input-short" />

            <?php if ($this->errorWithdrawAddress): ?>
                <p class="errors"><?php echo $this->translate('Invalid withdraw address.'); ?></p>
            <?php endif; ?>

					<a href="#" onclick="$(this).parents('form').submit();" class="green-btn"><span>Invest</span></a>
				</form>
			</div>
			
		</div>
		<a href="#" id="login-close" class="close-overlay-block"></a>
	</div>
</div>

<script type="text/javascript">
    
$('#invest-form input').keydown(function(e) {
    if (e.keyCode == 13) {
        $('#invest-form').submit();
    }
});

</script>


          