<?php if ($this->pageCount): ?>
    <div class="paginationControl">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt; <?php echo $this->translate('Предишна'); ?></a> |
        <?php else: ?>
            <span class="disabled">&lt; <?php echo $this->translate('Предишна'); ?></span> |
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a> |
            <?php else: ?>
                <?php echo $page; ?> | 
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->url(array('page' => $this->next)); ?>"><?php echo $this->translate('Следваща'); ?> &gt;</a>
        <?php else: ?>
            <span class="disabled"><?php echo $this->translate('Следваща'); ?> &gt;</span>
        <?php endif; ?>
    </div>
<?php endif; ?>