<div class="box" id="box-0">
    <h4 class="box-header round-top"><i class="icon-list-alt"></i></h4>
        <div class="box-container-toggle">
            <div class="box-content form-box">
				<form class="form-horizontal" action="" method="post">
<div class="control-group">
        <?php echo $this->form->getElement('title'); ?>
</div>
                                    <div class="control-group">
        <?php echo $this->form->getElement('slug'); ?>
</div>
<div class="control-group">
        <?php echo $this->form->getElement('content'); ?> 
</div>       
<div class="control-group">
        <?php echo $this->form->getElement('meta_keywords'); ?>
</div>
<div class="control-group">
        <?php echo $this->form->getElement('meta_description'); ?>
</div>

<div class="form-actions">        
        <?php echo $this->form->getElement('save'); ?>
</div>

</form>
</div>
</div>
</div>