<?php

    $btcuser = Zend_Registry::get('config')->btc->conn->user;
    $btcpass = Zend_Registry::get('config')->btc->conn->pass;
    $btcurl = Zend_Registry::get('config')->btc->conn->host;
  $bitcoin = new App_jsonRPCClient('http://'.$btcuser.':'.$btcpass.'@'.$btcurl.'/');
  
 //$account = $bitcoin->getaccountaddress('account_1');
  # now check for appropriate funds in user account
  //
  //$account = $bitcoin->getnewaddress(); //param ($account)
 // $account = $bitcoin->getbalance();
 $account = $bitcoin->listaccounts();
 //$account = $bitcoin->getbalance('account_16');
 // 
 //$account = $bitcoin->listaccounts();
 //$account = $bitcoin->getbalance('account_1');
 // $account = $bitcoin->validateaddress('1MBLjrp2v23iucHgZxDydJE6Xt1frZLnZ3');
  //this returns array:
//  array(7) {
//  ["isvalid"] => bool(true)
//  ["address"] => string(34) "1GXcc2sxZ4j28DF4iSeKjamcjNtzSw9Bqx"
//  ["ismine"] => bool(true)
//  ["isscript"] => bool(false)
//  ["pubkey"] => string(66) "0301b84d859b83c792d44f1f28535002c7f00094fe85d5e0cbd6ab3fcbf555d668"
//  ["iscompressed"] => bool(true)
//  ["account"] => string(0) ""
//}
  
 // //lists all addresses in the current account/server
  
  //$bitcoin->walletpassphrase('2l33t4u2',1000); - must unlock before dumping
  //$account = $bitcoin->dumpprivkey('1GXcc2sxZ4j28DF4iSeKjamcjNtzSw9Bqx');
  //L3Amz5LEEogXDRHjYZzemDhDbfJ9r9skX2Ytv5ZCbXJuvFmcjKjA
   Zend_Debug::dump($account);exit;?>