<!-- FOOTER -->
<div class="footer-wrapper">
	<div class="after-header-line"></div>
	<div class="footer-shadow">
		<ul class="footer-holder">
			<li>
				<span class="f-title">Still not a member?</span>
				<span class="f-text">Become a member and explore our full features.</span>
				<a href="#" class="register-btn"><span>Join now</span></a>
				<span class="copyright">Copyright © 2012 BitLendingClub.</span>
			</li>
			<li>
				<span class="f-title">How it works?</span>
				<a href="#">See for yourselfes how our soft works</a>
			</li>
			<li>
				<span class="f-title">Investing</span>
				<a href="#">Overview</a>
				<a href="#">Browse Listings</a>
				<a href="#">Create automated plan</a>
			</li>
			<li>
				<span class="f-title">About us</span>
				<a href="#">Our Company</a>
				<a href="#">History</a>
				<a href="#">Press</a>
				<a href="#">Blog</a>
			</li>
			<li>
				<span class="f-title">Help</span>
				<a href="#">Help &amp; FAQ</a>
				<a href="#">Terms &amp; Conditions</a>
				<a href="#">Privacy policy</a>
			</li>
			<li class="last">
				<span class="f-title">Contacts</span>
				<span class="small-f-title">Phone:</span>
				<span class="phone">(617) 555-1585</span>
				<span class="small-f-title">Email:</span>
				<a href="#" class="e-mail">hello@bitlendingclub.com</a>
				<ul>
					<li><a href="#" class="facebook"></a></li>
					<li><a href="#" class="twitter"></a></li>
					<li><a href="#" class="linkedin"></a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>


</body>
</html>