<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <?php echo $this->headMeta(); ?>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <?php
        echo $this->headScript()
                ->prependFile('/js/jquery-1.7.1.min.js')
                ->appendFile('/js/jquery-ui-1.8.18.custom.min.js')
                ->appendFile('/js/jquery.lightbox-0.5.min.js')
                ->appendFile('//connect.facebook.net/en_US/all.js')
                ->appendFile('/js/jqModal.js')
                ->appendFile('/js/default.js');
        ?>
        <?php
        echo $this->headLink()
                ->prependStylesheet('/styles/reset.css')
                ->appendStylesheet('/styles/main-style.css')
                ->appendStylesheet('/styles/jqModal.css')
                ->appendStylesheet('/styles/jquery.lightbox-0.5.css')
                ->appendStylesheet('/styles/smoothness/jquery-ui-1.8.18.custom.css');
        ?>
        <title>BitLendingClub</title>

        <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,700,300italic,400italic,700italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    </head>
    <body>


        <!-- HEADER -->
        <div class="header-wrapper">
            <div class="header-glow">
                <div class="header-holder">
                    <a href="/" class="logo"></a>
                    <?php
                            $partial = array('menu.phtml', 'default');
                            $this->navigation()->menu($this->navigation)->setPartial($partial);
                            echo $this->navigation()->menu($this->navigation)->setMaxDepth(1)->render();
                        ?>
<!--                    <ul id="main-nav">
                        <li><a href="#"><span><span class="blue-ring">How it works?</span></span></a></li>
                        <li><a href="#"><span><span class="green-ring">Investing</span></span></a></li>
                        <li><a href="#"><span><span class="yellow-ring">About us</span></span></a></li>
                        <li><a href="#"><span><span class="orange-ring">Help</span></span></a></li>
                    </ul>-->
                    <?php if (Zend_Auth::getInstance()->getIdentity()): ?>

                        <ul class="account-wrapper">
                            <li class="last selected">
                                <a href="#" class="login"><span><span>My Account</span></span></a>
                                <div class="dropdown-menu-wrapper">
                                    <div class="dropdown-menu-holder">
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'index'), null, true); ?>">Dashboard</a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->url(array('controller' => 'rating', 'action' => 'index'), null, true); ?>">Credit rating</a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'reputation'), null, true); ?>">Reputation</a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'investments'), null, true); ?>">Investments</a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'loans'), null, true); ?>">Loans</a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'settings'), null, true); ?>">Settings</a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout'), null, true); ?>">Sign out</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    <?php else: ?>

                        <ul class="account-wrapper">
                            <li><a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'register'), null, true); ?>" class="register-btn"><span>Join now</span></a></li>
                            <li class="last"><a href="#" class="login" id="login-button"><span>Login</span></a></li>
                        </ul>

                    <?php endif; ?>
                </div>
            </div>
            <div class="after-header-line"></div>
        </div>