<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <?= $this->headTitle(); ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php 
        echo $this->headMeta(); 
        
        echo $this->headScript()
                ->prependFile('/js/jquery-1.7.1.min.js')
                ->appendFile('/js/script.js');
       
        
        echo $this->headLink()
                ->prependStylesheet('http://fonts.googleapis.com/css?family=Ubuntu:400,700')
                ->appendStylesheet('/styles/style.css');
    ?>
    
    <!--[if lt IE 8]>
      <div style=' clear: both; text-align:center; position: relative;'>
        <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
          <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
       </a>
     </div>
    <![endif]-->
    <!--[if lt IE 9]>
        <?php 
            echo $this->headScript()
                    ->prependFile('/js/html5.js');

            echo $this->headLink()
                    ->appendStylesheet('/css/ie.css');
        ?>
    <![endif]-->

</head>
<body>
          
            <?php echo $this->layout()->content; ?>
       
</body>
</html>