<div id="page-wrapper">

    <header id="page-header">
        <h1><?php echo $this->translate('Change Your Password'); ?></h1>
    </header>

    <?php echo $this->partial('settings/navigation.phtml'); ?>
    <section id="page-container">
        <section id="page-section">
            
            <h2><?php echo $this->translate('Change E-mail - Not implemented yet'); ?></h2>            
            
        </section>
    </section>


    <footer id="page-footer">
        <p>&copy; <?php echo $this->translate('2012 Grouper.mk Сите права задржани.'); ?></p>
    </footer>

</div>