<div id="page-wrapper">
    
    <header id="page-header">
        <h1><?php echo $this->translate('Personal Information'); ?></h1>
    </header>

    <?php echo $this->partial('settings/navigation.phtml'); ?>
    <section id="page-container">
        <section id="page-section">
            
            <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>

            <?php if ($flashMessenger->setNamespace('success')->hasMessages()): ?>
                <div class="form-message-success">
                <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                    <p><?php echo $msg ?></p>
                <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if ($flashMessenger->setNamespace('error')->hasMessages()): ?>
                <div class="form-message-error">
                <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                    <p><?php echo $msg ?></p>
                <?php endforeach; ?>
                </div>
            <?php endif; ?>        
            
            <h2><?php echo $this->translate('Personal Data'); ?></h2>            
            
            <?php echo $this->partial('settings/personal/form.phtml', array('form' => $this->form)); ?>            
        </section>
    </section>
    
    
    <footer id="page-footer">
        <p>&copy; <?php echo $this->translate('2012 Grouper.mk Сите права задржани.'); ?></p>
    </footer>
    
</div>