<div id="page-wrapper">

    <header id="page-header">
        <h1><?php echo $this->translate('Subscriptions'); ?></h1>
    </header>

    <?php echo $this->partial('settings/navigation.phtml'); ?>

    <section id="page-container">
        <section id="page-section">
            <form action="" method="post">
                <h2><?php echo $this->translate('Одбери кои категории те интересираат да се subscribe.'); ?></h2>
                <p><?php echo $this->translate('Тука може да одбереш за кои типови на понуди и од кои градови сакаш да ги добиваш на E-mail известување '); ?></p>

                <ul id="subscription-category">
                    <?php foreach ($this->categories as $category) : ?>
                        <li <?php if (in_array($category->getId(), $this->subscriptionCatsOpts)) : ?>class="checked" <?php endif; ?>>
                            <div>
                                <?php echo $this->formCheckbox('categories[]', $category->getId(), array('checked' => (in_array($category->getId(), $this->subscriptionCatsOpts) ?  true : false))); ?>
                            </div>
                            <div class="description">
                                <h3><?php echo $category->getName(); ?></h3>
                                <?php if ($category->getDescription()): ?>
                                    <p><?php echo $category->getDescription(); ?></p>
                                <?php endif; ?>
                            </div>
                        </li>                

                    <?php endforeach; ?>
                    
                </ul>

                <h2><?php echo $this->translate('Одбери од кои градови да добиваш зделки:'); ?></h2>

                <ul id="subscription-city">
                    <?php foreach ($this->cities as $city) : ?>
                    <li><?php echo $this->formCheckbox('cities[]', $city->getId(), array('checked' => (in_array($city->getId(), $this->subscriptionCitiesOpts) ?  true : false))); ?> <?php echo $city->getName(); ?></li>
                    <?php endforeach; ?>
                </ul>    

                <p>
                    <?php echo $this->formCheckbox('event_friends', 1, array('checked' => ($this->subscription != null ? $this->subscription->getFriendEvent() : false))); ?>
                    <?php echo $this->translate('Извести ме по e-mail кога некој ке ме додаде за пријател.'); ?>
                </p>

                <p>
                    <?php echo $this->formCheckbox('event_comments', 1, array('checked' => ($this->subscription != null ? $this->subscription->getMessageEvent() : false))); ?>
                    <?php echo $this->translate('Извести ме по e-mail кога некој ке ми пише приватна порака.'); ?>
                </p>

                <p>
                    <?php echo $this->formSubmit('submit', 'Submit', array('class' => 'button')); ?>
                </p>


            </form>        

        </section>        
    </section>

    <footer id="page-footer">
        <p>&copy; <?php echo $this->translate('2012 Grouper.mk Сите права задржани.'); ?></p>
    </footer>

</div>

