<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />        
        <?php echo $this->headScript()
                ->prependFile('/js/jquery-1.7.1.min.js')
                ->appendFile('/js/jquery-ui-1.8.18.custom.min.js')
                ->appendFile('/js/jquery.filedrop.js')
                ->appendFile('/js/jqModal.js')
                ->appendFile('/js/jquery-ui-timepicker-addon.js')
                ->appendFile('/js/jquery.slug.js')
                ->appendFile('/js/admin.js');?>
        <?php
        echo $this->headLink()
                ->prependStylesheet('/styles/main.css')
                ->appendStylesheet('/styles/bootstrap.min.css')
				->appendStylesheet('/styles/bootstrap-responsive.css')
                ->appendStylesheet('/styles/jqModal.css')
                ->appendStylesheet('/styles/smoothness/jquery-ui-1.8.18.custom.css');
        ?>
        <title><?php echo $this->translate('Administration Panel'); ?></title>
        <base href="<?php echo $this->url(array('module' => 'admin'), null, true);?>/" />
     
    </head>
    <body id="dashboard">               
	<div class="main-nav-wrapper hidden-phone">
    		<div class="navbar navbar-top main-nav">
        		<div class="navbar-inner">
            			<div class="container-fluid ">
                			<div class="nav-collapse">
                    				<ul class="nav">
                            <?php  $partial = array('menu.phtml', 'admin'); $this->navigation()->menu()->setPartial($partial); ?>
							<?php echo $this->navigation()->menu(); ?>
						</ul>
                			</div><!--/.nav-collapse -->
            			</div>

        		</div>
    		</div>
	</div>
	<div class="container-fluid">
		<div class="row-fluid">
 			<div class="span12">
				<?php echo $this->layout()->content ?>
			</div>
		</div>
	</div>
        <div class="jqmWindow" id="main-modal-dialog"></div>
        <!--div class="logout"><a href="<?php echo $this->url(array('module' => "admin", 'controller' => 'logout', 'action' => 'logout'));?>">Logout</a></div-->
    </body>
</html>