<section>
    <form method="post" enctype="multipart/form-data">
        <section>
            <dl>
               
            </dl>
        </section>
        <div class="delimiter"></div>
        <section class="submit">
            <dl>
                <?php echo $this->form->getElement('save'); ?>
                <?php echo $this->form->getElement('cancel'); ?>
            </dl>
        </section>
    </form>
</section>
