<section id="page-section">

    <header>
        <h2><?php echo $this->translate('Documents'); ?></h2>
        
    </header>

    <section>
        <table class="list-table" >
            <colgroup>
                <col width="*" />
                <col width="25%" />
                <col width="10%" />
                <col width="20%" />
                <col width="10%" />
            </colgroup>    
            <thead>
                <tr>
                    <th><?php echo $this->translate('Document Path'); ?></th>
                    <th><?php echo $this->translate('Document Type'); ?></th>
                    <th><?php echo $this->translate('By User'); ?></th>
                    <th><?php echo $this->translate('Uploaded On'); ?></th>   
                    <th><?php echo $this->translate('Is Reviewed?');?></th>
                    <th><?php echo $this->translate('Reviewed By'); ?></th>
                    <th class="center"><?php echo $this->translate('Actions'); ?></th>
                </tr>
            </thead>

            <tfoot>
                <tr>
                    <td colspan="20">
                        <?php echo $this->paginationControl(
                                $this->docsList, 'Sliding', 'partials/paginator.phtml'); ?>                
                    </td>
                </tr>
            </tfoot>

            <tbody>
                <?php if ($this->docsList->getTotalItemCount() > 0): ?>
                    <?php foreach ($this->docsList as $doc): ?>
                        <tr>
                            
                            <td><?php echo $doc->getDocumentPath();?></td>
                            <td><?php echo $doc->getDocumentType()->getName();?></td>
                            <td><?php echo $doc->getUser()->getFullName();?></td>
                            <td><?php echo $this->date($doc->getCreatedAt());?></td>
                            <td><?php if($doc->getIsReviewed()) {echo $this->translate('Yes');} else {echo $this->translate('No');}?></td>
                             <td><?php if($doc->getReviewer()) echo $doc->getReviewer()->getFullName();?></td>
                            <td class="center">                          
                                <!--a class="link-button-update" href="<?php echo $this->url(array('action' => 'update', 'id' => $doc->getId())); ?>" title="<?php echo $this->translate('Update'); ?>">
                                    <img src="/images/update.png" alt="" />
                                </a-->
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="20"><?php echo $this->translate('No documents found.'); ?></td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </section>

</section>    