<?php if ($this->pageCount): ?>
    <ul>
                            <!-- pagination next/previous classes ( .prev, .no-prev, .next, .no-next ) -->
                           
                            
                        
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>" class="arr prev"></a></li>
        <?php else: ?>
            <li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>" class="arr no-prev"></a></li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
            <?php else: ?>
                <li class="current"><?php echo $page; ?></li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li><a href="<?php echo $this->url(array('page' => $this->next)); ?>" class="arr next"></a></li>
        <?php else: ?>
            <li><a href="<?php echo $this->url(array('page' => $this->next)); ?>" class="arr no-next"></a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>