<div class="page-section-activity-item">
    <div class="activity-type">
        <img src="/images/badge.png" alt="" />
    </div>
    <div class="activity-user-badge">
        <img src="/images/badge_facebook.png" alt="" />
    </div>
    <div class="activity-message">
        <h3><?php echo $this->params['message'] ?></h3>
        <p><?php echo $this->date($this->params['date']) ?>.</p>
    </div>
</div>  