<div id="overlay-block">
	<div class="login-wrapper">
		<div class="login-holder">
			<div id="show-login-holder">
				<div class="title">Add funds to your account</div>
				To fund your account send bitcoins to the address bellow:
                                <div class="title" style="border-bottom:0!important;"><?php echo $this->wallet->getWalletPath();?></div>
			</div>
			
		</div>
		<a href="#" id="login-close" class="close-overlay-block"></a>
	</div>
</div>



          