<div id="main-wrapper">
    <ul id="tabs-nav">
        <li class="selected"><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'index'), null, true); ?>"><span class="dashboard-icon">Dashboard</span></a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'rating', 'action' => 'index'), null, true); ?>"><span class="crating-icon">Credit rating</span></a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'reputation'), null, true); ?>"><span class="rep-icon">Reputation</span></a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'investments'), null, true); ?>"><span class="overview-icon">Investments</span></a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'loans'), null, true); ?>"><span class="loan-icon">Loans</span></a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'settings'), null, true); ?>"><span class="automated-plan-icon">Settings</span></a></li>
    </ul>
    <div class="profile-content-wrapper">
        <div class="row">
            <div class="box box1 first">
                <div class="title">Account Balance</div>
                <div class="contnet">
                    <?php if (count($this->wallets) > 0): ?>
                        <?php foreach ($this->wallets as $wallet): ?>
                            <ul>
                                <li>BTC: <span><?php echo $wallet->getBalance(); ?></span></li>
                                <li>Unconfirmed: <span><?php echo $wallet->getBalance(); ?></span></li>
                            </ul>
                            <?php break; ?>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <ul>
                            <li>BTC: <span>0</span></li>
                            <li>Unconfirmed: <span>0</span></li>
                        </ul>
                    <?php endif; ?>
                    <div class="btns-set">
                        <a id="dash-add-funds" href="#" class="grey-small-btn"><span>Add funds</span></a>
                        <a id="dash-withdraw" href="#" class="grey-small-btn"><span>Withdraw</span></a>
                    </div>
                </div>
            </div>
            <div class="box box1">
                <div class="title">Reputation <span class="red"><?php echo $this->user->getRatingPercentage();?> %</span></div>
                <div class="contnet">
                    <ul>
                        <li>Positive: <span class="green"><?php echo $this->user->getPositiveRating(); ?></span></li>
                        <li>Negative: <span class="red"><?php echo $this->user->getNegativeRating(); ?></span></li>
                    </ul>
                    <div class="btns-set">
                        <a href="#" class="grey-small-btn"><span>Bitcoin OTC</span></a>
                        <a href="#" class="green-small-btn"><span>Rate user</span></a>
                    </div>
                </div>
            </div>
            <div class="box box1">
                <div class="title">Loans</div>
                <div class="contnet">
                    <ul>
                        <li>Funding in progress: <span><?php echo count($this->loans); ?></span></li>
                        <li>Active: <span><?php echo count($this->loans); ?></span></li>
                    </ul>
                    <div class="btns-set">
                        <a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'loans'), null, true); ?>" class="grey-small-btn"><span>My Loans</span></a>
                        <a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'create'), null, true); ?>" class="green-small-btn"><span>Get a loan</span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="box box1 first">
                <div class="title">Investments</div>
                <div class="contnet">
                    <ul>
                        <li>Pending: <span><?php echo count($this->investments); ?></span></li>
                        <li>Active: <span><?php echo count($this->investments); ?></span></li>
                    </ul>
                    <div class="btns-set">
                        <a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'investments'), null, true); ?>" class="grey-small-btn"><span>My investments</span></a>
                        <a href="<?php echo $this->url(array('controller' => 'loan', 'action' => 'index'), null, true); ?>" class="green-small-btn"><span>Browse listings</span></a>
                    </div>
                </div>
            </div>
            <div class="box box2">
                <div class="title">Credit Rating <?php if($this->validated==4): echo '<span class="green">'.$this->validated.'</span>'; else:  echo '<span class="red">'.$this->validated.'</span>'; endif; ?><span class="divider">/</span><span class="green">4</span></div>
                <div class="contnet">
                    <ol>
                        <li>Identity verified: <?php if($this->valId): echo '<span class="green">Yes</span>'; else: echo '<span class="red">No</span>'; endif;?></li>

                        <li>Address verified: <?php if($this->valAddress): echo '<span class="green">Yes</span>'; else: echo '<span class="red">No</span>'; endif;?></li>

                        <li>Facebook: <?php if($this->user->getFbUserId()): echo '<span class="green">Yes</span>'; else: echo '<span class="red">No</span>'; endif;?></li>
                        <li>Gmail: <span class="red">No</span></li>
                    </ol>
                    <div class="btns-set">
                        <a href="<?php echo $this->url(array('controller' => 'rating', 'action' => 'index'), null, true); ?>" class="green-small-btn"><span>Improve it</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>





