<div id="main-wrapper">
	<ul id="tabs-nav">
		<li class="selected"><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'index'), null, true); ?>"><span class="dashboard-icon">Dashboard</span></a></li>
		<li><a href="#"><span class="crating-icon">Credit rating</span></a></li>
		<li><a href="#"><span class="rep-icon">Reputation</span></a></li>
		<li><a href="#"><span class="overview-icon">Investments</span></a></li>
		<li><a href="#"><span class="loan-icon">Loans</span></a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'settings'), null, true); ?>"><span class="automated-plan-icon">Settings</span></a></li>
	</ul>
	<div class="profile-content-wrapper">
		<div class="full-width">
			<h1>Welcome to your Dashboard</h1>
			
					
				
			</form>
		</div>
	</div>
</div>

            
            
           
            
        