<div id="main-wrapper">
	<ul id="tabs-nav">
		<li><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'index'), null, true); ?>"><span class="dashboard-icon">Dashboard</span></a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'rating', 'action' => 'index'), null, true); ?>"><span class="crating-icon">Credit rating</span></a></li>
		<li class="selected"><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'reputation'), null, true); ?>"><span class="rep-icon">Reputation</span></a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'investments'), null, true); ?>"><span class="overview-icon">Investments</span></a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'loans'), null, true); ?>"><span class="loan-icon">Loans</span></a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'settings'), null, true); ?>"><span class="automated-plan-icon">Settings</span></a></li>
	</ul>
	<div class="profile-content-wrapper">
		<div class="sidebar-left profile-sidebar">
			<div class="sidebar-infoboard mb-twenty">
				<div class="sidebar-msg">
					<span>Import your Bitcoin OTC Reputation</span>
					<a href="#" class="green-btn"><span>Import</span></a>
				</div>
			</div>
			<div class="sidebar-infoboard">
				<div class="title">Reputation <span class="red"><?php echo $this->user->getRatingPercentage();?> %</span></div>
				<!--ul>
					<li>Positive: <span class="green">4</span></li>
					<li>Negative: <span class="red">17</span></li>
				</ul-->
			</div>
		</div>
		<div class="profile-content-right pcr-padding">
			<div class="page-title">
				<h1>Ratings</h1>
				<div class="table-toolbar">
					<div class="toolbar-sorter">
						<span>Show</span>
						<select>
							<option>10</option>
							<option>25</option>
							<option>50</option>
							<option>100</option>
						</select>
						<span>results.</span>
					</div>
					<div class="toolbar-search">
						<input type="text" />
						<a href="#"></a>
					</div>
				</div>
			</div>
			<!--table cellspacing="0" cellpadding="0">
				<thead>
					<tr>
						<th>From</th>
						<th>To</th>
						<th>Last update</th>
						<th>Rating</th>
						<th>Comment</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>2</td>
						<td>10</td>
						<td>21.12.2012</td>
						<td>10</td>
						<td class="comment">Lorem ipsum dolor sit amet, is a type printing era...</td>
						<td></td>
					</tr>
					<tr>
						<td>2</td>
						<td>10</td>
						<td>21.12.2012</td>
						<td>10</td>
						<td class="comment">Lorem ipsum dolor sit amet, is a type printing era...</td>
						<td></td>
					</tr>
					<tr>
						<td>2</td>
						<td>10</td>
						<td>21.12.2012</td>
						<td>10</td>
						<td class="comment">Lorem ipsum dolor sit amet, is a type printing era...</td>
						<td></td>
					</tr>
					<tr>
						<td>2</td>
						<td>10</td>
						<td>21.12.2012</td>
						<td>10</td>
						<td class="comment">Lorem ipsum dolor sit amet, is a type printing era...</td>
						<td></td>
					</tr>
					<tr>
						<td>2</td>
						<td>10</td>
						<td>21.12.2012</td>
						<td>10</td>
						<td class="comment">Lorem ipsum dolor sit amet, is a type printing era...</td>
						<td></td>
					</tr>
					<tr>
						<td>2</td>
						<td>10</td>
						<td>21.12.2012</td>
						<td>10</td>
						<td class="comment">Lorem ipsum dolor sit amet, is a type printing era...</td>
						<td></td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<td colspan="6" class="paging">
							<div class="listing-infotext">Showing <strong>1</strong> to <strong>10</strong> of  <span>44 entries</span></div>
							<ul>
								
								<li><a href="#" class="arr no-prev"></a></li>
								<li class="current">1</li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">4</a></li>
								<li><a href="#" class="arr next"></a></li>
							</ul>
						</td>
					</tr>
				</tfoot>
			</table-->
                        <div>No ratings found.</div>
			<div class="buttons-set m-twenty">
				<a href="#" class="green-btn"><span>Rate a user</span></a>
			</div>
		</div>
	</div>
</div>