<div id="register-section">
    
    <header>
        <h2><?php echo $this->translate('User Settings'); ?></h2>
        
            
      
    </header>    
    <div id="register-container">
        <section class="register-details">

            <form action="<?php echo $this->url(array('module' => 'default', 
                'controller' => 'profile', 'action' => 'settings'), null, true); ?>" method="post" onsubmit="return doUpdate(this);">
            <dl>
                

                <?php echo $this->form->getElement('password'); ?>
                
                <?php echo $this->form->getElement('password_confirm'); ?>                
                
                <?php echo $this->form->getElement('firstname'); ?>
                
                <?php echo $this->form->getElement('lastname'); ?>
                
                <?php echo $this->form->getElement('username'); ?>
                
                <?php echo $this->form->getElement('address'); ?>
                
               
            </dl>
            
           
            
            <p id="register-button-section">
              <?php echo $this->form->getElement('save'); ?>
               
            </p>
            
            </form>
        </section> 
    </div>    
</div>