<div id="overlay-block">
	<div class="login-wrapper">
		<div class="login-holder">
			<div id="show-login-holder">
				<div class="title">Withdraw Funds</div>
				<form id="withdraw-form" action="<?php echo $this->url(array('module' => 'default', 
                'controller' => 'profile', 'action' => 'withdraw'), null, true); ?>" method="post" >
					<?php echo $this->form->getElement('amount'); ?>
                <?php echo $this->form->getElement('address'); ?>

            <?php if ($this->errorWithdrawCredentials): ?>
                <p class="errors"><?php echo $this->translate('Invalid form data.'); ?></p>
            <?php endif; ?>

					<a href="#" onclick="$(this).parents('form').submit();" class="green-btn"><span>Withdraw</span></a>
				</form>
			</div>
			
		</div>
		<a href="#" id="login-close" class="close-overlay-block"></a>
	</div>
</div>

<script type="text/javascript">
    
$('#withdraw-form input').keydown(function(e) {
    if (e.keyCode == 13) {
        $('#login-form').submit();
    }
});

</script>


          